# Support Vector Machine Assignment-2

Q1. What is the relationship between polynomial functions and kernel functions in machine learning
algorithms?

Polynomial functions and kernel functions are both used in machine learning, particularly in support vector machines (SVMs). Polynomial functions introduce non-linear transformations to data, while polynomial kernels, a type of kernel function, compute the similarity between pairs of data points after applying polynomial transformations. This allows SVMs to capture non-linear relationships between features without explicitly computing the transformed feature space.







Q2. How can we implement an SVM with a polynomial kernel in Python using Scikit-learn?

i am just giving here an example

from sklearn.svm import SVC

then split your data in train and test

then make an instance of SVC

svc_classifier = SVC(kernel = "poly ", degree = 3) # degree specifies the degree of the polynomial kernel # Choose kernel as poly for polynomial

in that way we can implement SVM with a polynomial kernel

after doing all this we can do our further work on our model like train the classifier , make predictions , check accuracy and so on..

It is a just an example okey...

Q3. How does increasing the value of epsilon affect the number of support vectors in SVR?

Increasing the value of epsilon in Support Vector Regression (SVR) widens the tolerance margin for errors. This leads to a smoother regression function and fewer support vectors because the model becomes more tolerant to deviations from the predicted values.







Q4. How does the choice of kernel function, C parameter, epsilon parameter, and gamma parameter
affect the performance of Support Vector Regression (SVR)? Can you explain how each parameter works
and provide examples of when you might want to increase or decrease its value?

1) Kernel Function: Determines the complexity of relationships captured by the model.

. Use RBF for non-linear, linear for linear, and polynomial for polynomial relationships.

2) C Parameter: Controls the trade-off between smoothness and error tolerance.

. Increase for less tolerance to errors, decrease for more tolerance.

3) Epsilon Parameter: Sets the width of the epsilon-tube around predicted values.

. Increase for wider margin of tolerance, decrease for stricter tolerance.

4) Gamma Parameter: Affects the reach of the kernel function.

. Increase for more complex decision boundaries, decrease for smoother boundaries.

Q5. Assignment:

In [2]:
from sklearn.datasets import load_wine
wine = load_wine()

In [3]:
wine.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [5]:
import pandas as pd

df = pd.DataFrame(wine.data , columns=wine.feature_names)

In [6]:
df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
dtypes: fl

In [8]:
df.shape

(178, 13)

In [9]:
df["Target"] = wine.target

In [10]:
df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  Target  
0                          3.92   1065.0       0  
1                          3.40   1050.0       0  
2                          3.17   1185.0       0  
3                          3.45   1480.0       0  
4                          2.93    735.0       0

In [11]:
df["Target"].value_counts()

1    71
0    59
2    48
Name: Target, dtype: int64

In [12]:
# So here i will importing some libraries which we are going to use in creating our model

import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split 
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score , classification_report , confusion_matrix
from sklearn.model_selection import GridSearchCV

In [13]:
# So here we have our data i am taking wine dataset
df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  Target  
0                          3.92   1065.0       0  
1                          3.40   1050.0       0  
2                          3.17   1185.0       0  
3                          3.45   1480.0       0  
4                          2.93    735.0       0

In [14]:
# here i will split my data into train and test

X = df.drop("Target",axis=1)
y = df["Target"]

In [15]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.2 , random_state = 42)

In [16]:
X_train.shape , y_train.shape

((142, 13), (142,))

In [17]:
# here i will use standardscaler to preprocess the data

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [19]:
 X_train_scaled.shape , X_test_scaled.shape

((142, 13), (36, 13))

In [20]:
# create an instance of svc classifier

svc_clf = SVC()

In [21]:
svc_clf.fit(X_train_scaled , y_train)

SVC()

In [22]:
y_pred = svc_clf.predict(X_test_scaled)

In [28]:
# Evaluate the performance of the model 

print("Accuracy: " , accuracy_score(y_pred , y_test))
print(confusion_matrix(y_pred , y_test))
print(classification_report(y_pred , y_test))

Accuracy:  1.0
[[14  0  0]
 [ 0 14  0]
 [ 0  0  8]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00         8

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36



In [33]:
# Tune hyperparameter using gridsearchcv

# here i defined my parameters


parameters = {"kernel": ["linear", "poly" , "rbf"],
             "gamma": [0.1 ,0.01 , 0.001 , 0.0001], 
             "C":[0.1 , 1 , 10 , 100 ]}

In [34]:
grid_search = GridSearchCV(svc_clf , param_grid = parameters ,cv = 5)

In [35]:
grid_search.fit(X_train_scaled , y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100],
                         'gamma': [0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['linear', 'poly', 'rbf']})

In [40]:

print("Best_parameters: {}".format(grid_search.best_params_))

Best_parameters: {'C': 1, 'gamma': 0.01, 'kernel': 'rbf'}


In [42]:
# So here we got the best parameters for our model 

svc_classifier = SVC(kernel = "rbf", gamma = 0.01 , C = 1)

svc_classifier.fit(X_train_scaled , y_train)

SVC(C=1, gamma=0.01)

In [43]:
y_pred = svc_classifier.predict(X_test_scaled)

In [44]:
y_pred

array([0, 0, 2, 0, 1, 0, 1, 2, 1, 2, 0, 2, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 2, 2, 2, 1, 1, 1, 0, 0, 1, 2, 0, 0, 0])

In [47]:
## will check the accuracy of the model now with the best parameters

print("Accuracy: {} ".format(accuracy_score(y_pred , y_test)))
print("Confusion matrix: {}".format(confusion_matrix(y_pred , y_test)))
print("Classification report: {}".format(classification_report(y_pred , y_test)))

Accuracy: 1.0 
Confusion matrix: [[14  0  0]
 [ 0 14  0]
 [ 0  0  8]]
Classification report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00         8

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36



In [48]:
import joblib

In [50]:
filename = "svc_classifier.sav"

joblib.dump(svc_classifier , filename)

['svc_classifier.sav']

In [52]:
## Save the trained classifier to the file